production:
  bucket: cmusv-rails-mfse-test
  enabled: false
development:
  bucket: cmusv-rails-mfse-development
  enabled: false
  revision: 45c2
staging:
  bucket: cmusv-rails-mfse-test
  enabled: false
test:
  delete_prev_rev: true
  bucket: cmusv-rails-mfse-test
  s3_logging_enabled: false
  enabled: false
  revision: "20100316165112"
